name: Build container image

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: burpai-mitmproxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate version number
        run: echo "IMAGE_VERSION=$(python3 -c "import datetime; d=datetime.datetime.now().timetuple(); print(f'{d.tm_year:04}.{d.tm_yday:03}.{d.tm_hour:02}{d.tm_min:02}{d.tm_sec:02}')")" >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

      - name: Create release
        env:    
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            export IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            gh release create ${{ env.IMAGE_VERSION }} --target ${{ github.sha }}
            envsubst < docker-compose.yaml.template > docker-compose.yaml
            gh release upload ${{ env.IMAGE_VERSION }} docker-compose.yaml
